# Generated by Django 5.0.1 on 2026-02-15 17:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supabase_id', models.CharField(blank=True, help_text='UUID del cliente en Supabase (para sincronización)', max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('dni', models.CharField(blank=True, help_text='Documento de identidad', max_length=20, null=True, verbose_name='DNI/Pasaporte')),
                ('phone', models.CharField(help_text='Formato: +51987654321', max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('unit_number', models.CharField(max_length=50, verbose_name='Número de Unidad')),
                ('building', models.CharField(blank=True, max_length=50, null=True, verbose_name='Torre/Edificio')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Piso')),
                ('has_debt', models.BooleanField(default=False, verbose_name='Tiene Deuda')),
                ('debt_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto de Deuda')),
                ('last_payment_date', models.DateField(blank=True, null=True, verbose_name='Última Fecha de Pago')),
                ('preferred_contact_method', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('phone_call', 'Llamada Telefónica')], default='whatsapp', max_length=20, verbose_name='Método de Contacto Preferido')),
                ('notes', models.TextField(blank=True, help_text='Notas internas sobre el cliente')),
                ('is_active', models.BooleanField(default=True, help_text='Cliente activo en el sistema')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clients',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone'], name='clients_phone_459745_idx'), models.Index(fields=['email'], name='clients_email_4c8bec_idx'), models.Index(fields=['unit_number'], name='clients_unit_nu_ba71f2_idx'), models.Index(fields=['has_debt'], name='clients_has_deb_f0566f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(help_text='UUID de la conversación', max_length=100, unique=True)),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], help_text='Canal por el que se recibió el mensaje', max_length=20)),
                ('state', models.CharField(choices=[('waiting', 'Esperando Procesamiento'), ('processing', 'Procesando'), ('ai_resolved', 'Resuelto por IA'), ('fallback', 'Fallback Activado'), ('closed', 'Cerrado')], default='waiting', max_length=20)),
                ('quality_score', models.FloatField(blank=True, help_text='Score de calidad de la respuesta IA (0.0 - 1.0)', null=True)),
                ('used_fallback', models.BooleanField(default=False, help_text='Si se activó el Fallback Node')),
                ('fallback_reason', models.TextField(blank=True, help_text='Razón por la que se activó fallback', null=True)),
                ('trello_card_id', models.CharField(blank=True, help_text='ID de la tarjeta en Trello', max_length=100, null=True)),
                ('trello_card_url', models.URLField(blank=True, help_text='URL de la tarjeta en Trello', null=True)),
                ('trello_priority', models.CharField(blank=True, choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('URGENT', 'Urgente')], max_length=20, null=True)),
                ('context', models.JSONField(default=dict, help_text='Contexto de la conversación (intención, rag_results, etc.)')),
                ('metadata', models.JSONField(default=dict, help_text='Metadata adicional (IP, user agent, etc.)')),
                ('contact_snapshot', models.JSONField(blank=True, help_text='Datos de contacto del cliente al momento de la conversación', null=True)),
                ('processing_time_seconds', models.FloatField(blank=True, help_text='Tiempo total de procesamiento', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Cuándo se resolvió la conversación', null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='bot.client')),
            ],
            options={
                'db_table': 'conversations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente IA'), ('system', 'Sistema')], max_length=20)),
                ('content', models.TextField(help_text='Texto del mensaje o transcripción de audio')),
                ('attachments', models.JSONField(default=list, help_text='\n        Lista de archivos multimedia adjuntos.\n        Formato: [\n            {\n                "type": "audio|image|video|pdf",\n                "url": "/media/... o https://supabase...",\n                "filename": "archivo.ext",\n                "size_bytes": 12345,\n                "mime_type": "audio/ogg",\n                "transcription": "...",  # Solo para audio\n                "analysis": "...",       # Para imagen/pdf\n                "duration_seconds": 10   # Solo para audio/video\n            }\n        ]\n        ')),
                ('node_executed', models.CharField(blank=True, help_text='Qué nodo de LangGraph generó este mensaje', max_length=50, null=True)),
                ('processing_time_ms', models.IntegerField(blank=True, help_text='Tiempo de procesamiento en milisegundos', null=True)),
                ('telegram_message_id', models.BigIntegerField(blank=True, help_text='ID del mensaje en Telegram', null=True)),
                ('whatsapp_message_id', models.CharField(blank=True, help_text='ID del mensaje en WhatsApp', max_length=100, null=True)),
                ('gmail_message_id', models.CharField(blank=True, help_text='ID del mensaje en Gmail', max_length=100, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bot.conversation')),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['conversation_id'], name='conversatio_convers_144068_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['client', '-created_at'], name='conversatio_client__863387_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['state'], name='conversatio_state_a2f18f_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['used_fallback'], name='conversatio_used_fa_6e7e4e_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['trello_card_id'], name='conversatio_trello__c40520_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'timestamp'], name='messages_convers_31a2d0_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['role'], name='messages_role_8be1df_idx'),
        ),
    ]
